### ISSUE TITLE
Table with support testing

### ISSUE THREAD

**Issue by oscardssmith** [georgewhewell/undervolt#1]
It would be good to have a table for what configurations this is known to work for.

**Comment by georgewhewell** [comment]
Thanks, have added my config. If you can confirm working on your system please send PR with config :)

**Comment by oscardssmith** [comment]
How can I confirm that it worked? It didn't produce any output suggesting an error, but I don't know how to see what the voltage is.

**Comment by georgewhewell** [comment]
If it worked your temps/power usage should be a bit lower, and maybe your
system locks up if you apply too much undervolt! There is no 'read'
functionality yet- I will try to add this next.

**Comment by AndreaOrru** [comment]
Hey @georgewhewell thanks for this! Tested on a `Lenovo Yoga 920 - i7-8550U`, undervolting `-110mV` - it works :), you can add it to the table if you want.

**Comment by georgewhewell** [comment]
@AndreaOrru thanks- added!
