### ISSUE TITLE
thinkpad w550s works, but the setting is resetted whenever it is removed from the dock

### ISSUE THREAD

**Issue by guanghwang** [georgewhewell/undervolt#10]
Intel i7-5500U in thinkpad w550s works, but it needs to be re-applied whenever it is removed from or attached to the dock.  Is there a way that I could set the voltage permanently? Thank you.

Here is the undervolt result:
cache: -80.08 mV
analogio: 0.0 mV
gpu: -80.08 mV
uncore: 0.0 mV
core: -80.08 mV

**Comment by georgewhewell** [comment]
@guanghwang I think probably something in the machines firmware is resetting the offset. I don't think this will be easy to modify, but as a workaround you could either-

 - Configure udev to re-apply config on dock status change. Probably you will add something to your udev rules like:
`KERNEL=="dock.*", RUN+="/usr/local/bin/undervolt.py --core -80"`
 - Configure a cron job to re-apply offsets every minute or something

If you find a working solution please open a PR to update documentation :)
