### ISSUE TITLE
Why is it advised to schedule the task periodically ?

### ISSUE THREAD

**Issue by alexandremasanes** [georgewhewell/undervolt#103]
Running this service as a daemon might be performance hungry, might it not ? I just created a "oneshot" service which runs once on system boot and it works absolutely fine.

**Comment by georgewhewell** [comment]
There is some discussion of this in #45 but short answer is that it's hard to find a catch-all solution to events that reset, eg dock/undock/charge/sleep. You can set triggers for this if you only care about sleep/resume using example service in https://github.com/georgewhewell/undervolt/pull/101
