### ISSUE TITLE
Code not probably fully compatible with Python 2

### ISSUE THREAD

**Issue by Nicceboy** [georgewhewell/undervolt#13]
Code might not be fully working on Python 2. (When loading from ThrottleStop.ini)
When using Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
Getting following error:
```shell
nicce@nicce:$ sudo undervolt --throttlestop ThrottleStop.ini
Traceback (most recent call last):
  File "/usr/local/bin/undervolt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/undervolt.py", line 225, in main
    ts = config['ThrottleStop']
AttributeError: ConfigParser instance has no attribute '__getitem__'
```

I switched to Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
Works great.

Using Thinkpad X1 Yoga Gen2, Ubuntu 18.04, Linux Kernel 4.17

**Comment by Nicceboy** [comment]
I looked now at the code, and it was fine there. I copied source and ran it with Python 2 and 3, could not reproduce problem.
I guess problem only occurs, if you install it with pip for Python 2 first time. Installing with pip3 for Python 3 fixes the problem also when running in Python 2 (weird?). 
Could not reproduce by uninstalling both packages.
Quite mysterious...

**Comment by georgewhewell** [comment]
Hmm, seems like interface of `ConfigParser` changed between 2 and 3. I can replicate this with python2 (easier to invoke via `python undervolt.py` rather than relying on shebang)
Could you share your TS config file, and I will try to find way that works for both?

**Comment by Nicceboy** [comment]
Here is TS config file. Changed from .ini to .txt. 

[ThrottleStop.txt](https://github.com/georgewhewell/undervolt/files/2072659/ThrottleStop.txt)

**Comment by georgewhewell** [comment]
@Nicceboy Thanks! I think [this branch](https://github.com/georgewhewell/undervolt/tree/bug/throttlestop-py2k) should do it.

**Comment by Nicceboy** [comment]
I wasn't able to get error anyhow. Looks like fixed now. :smiley:
