### ISSUE TITLE
Followed instructions exactly and this is of course the errror code I get as usual with everything here Have to be a computer wizard programmer with 20 years of experience to get something simple to work.

### ISSUE THREAD

**Issue by fghjgsrhsdes3456** [georgewhewell/undervolt#135]
undervolt --read
modprobe: ERROR: could not insert 'msr': Operation not permitted
Traceback (most recent call last):
  File "/home/owner/.local/bin/undervolt", line 8, in <module>
    sys.exit(main())
  File "/home/owner/.local/lib/python3.8/site-packages/undervolt.py", line 386, in main
    subprocess.check_call(['modprobe', 'msr'])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['modprobe', 'msr']' returned non-zero exit status 1.

**Comment by jharwinbarrozo** [comment]
You have to run with sudo.

`sudo undervolt --read`

**Comment by trevluv** [comment]
> You have to run with sudo.
> 
> `sudo undervolt --read`

Now I am getting this error when I followed your advice.

owner@owner-Legion-Y540-15IRH:~$ sudo undervolt --read
sudo: undervolt: command not found

**Comment by georgewhewell** [comment]
`sudo python -m undervolt`
or
`sudo $(which undervolt)`
or
`sudo -E undervolt`

should work
