### ISSUE TITLE
Making change permanent?

### ISSUE THREAD

**Issue by dejIO** [georgewhewell/undervolt#14]
What's the best way to make the change permanent? Using Arch Linux.

**Comment by georgewhewell** [comment]
There is no way to make the change permanent in the sense of not having to run some utility- it will always be reset on reboot, suspend etc. There are some suggestions in #10 for re-applying changes automatically, or you can just run the command in a loop:

`watch -n 1 "undervolt --gpu -100"`

**Comment by dejIO** [comment]
This is what I did. I think it's working.

Note: For the compatibility list, I'm using a T460p with i5-6440HQ.

```
/etc/systemd/system/undervolt.service

[Unit]
Description=undervolt

[Service]
Type=oneshot
RemainAfterExit=true
ExecStart=/usr/bin/sudo undervolt -v --core -150 --cache -150 --gpu -100
[Install]
WantedBy=multi-user.target
```

**Comment by Xentradi** [comment]
Forgive me if this is the wrong way to go about it but couldn't it run with a cronjob in `crontab -e`?

`@reboot /path/to/undervolt.py -options`

If this is incorrect what would then be the most effective way?

**Comment by georgewhewell** [comment]
@Xentradi This should work for applying undervolt after boot, but I think you will find after suspend/resume the settings need to be re-applied, and cron will not do this.

**Comment by Xentradi** [comment]
@georgewhewell I noticed that after my comment. And have been working on a systemd based solution building upon what @dejIO used.

[https://gitlab.com/xentradi/undervoltWatcher](https://gitlab.com/xentradi/undervoltWatcher)
edit: github mirror: [https://github.com/Xentradi/undervoltWatcher](https://github.com/Xentradi/undervoltWatcher)

Combines a systemctl service with a watch script.
Service ensures the watcher is always running even if killed unless the service is stopped.
Watcher checks (every 5 seconds) to see if the core offset values are 0.0 if they are it applies the offsets. 
Of course this only works if you're changing your core offset but it can be changes pretty easily.

Also thank you for providing undervolt. It's by far the simplest solution for under-volting!

**Comment by georgewhewell** [comment]
Cool! Is there any reason you don't just apply the offset on every invocation? 'Reading' still involves writing to the register and reading back result, so the only difference is whether the 'read' bit is set.

**Comment by Xentradi** [comment]
Mostly for convenience, The values I have set are what I know are stable right now. I like to try different offsets to see what sort of results I can get. If it was setting at every invocation my tests would last all of 5 seconds; this way it will go till either I change it or the system sleeps/reboots.

**Comment by Oliph** [comment]
[deleted] -- No working as expected

**Comment by Xentradi** [comment]
@Oliph your offsets will reset on boot, and on wake from sleep/hibernation. I use a laptop so my offsets were getting reset when ever the lid was closed. The watcher corrects this while allowing me to still tweak the offsets when I want and I can reset them to something I know works as simply as closing the lid. I use that mostly because my schedule is unpredictable so I'm not always able to sit and test
