### ISSUE TITLE
Freeze when using systemd

### ISSUE THREAD

**Issue by burner1024** [georgewhewell/undervolt#141]
From cmd, undervolt appears to be working correctly:
```bash
$ sudo undervolt --gpu -100 --core -100 --cache -100 --uncore -100 --analogio -100
$ sudo undervolt --read
temperature target: -25 (75C)
core: -99.61 mV
gpu: -99.61 mV
cache: -99.61 mV
uncore: -99.61 mV
analogio: -99.61 mV
powerlimit: 25.0W (short: 0.00244140625s - disabled) / 25.0W (long: 28.0s - enabled)
```
But when I put it into a systemd unit as described in readme, and restart the service, the system freezes immediately.
Any tips?

**Comment by georgewhewell** [comment]
probably your offsets are too aggressive and are too much when your system is under load (during startup)- try reducing them a bit and testing with some load
