### ISSUE TITLE
unrecognized MSR 0x150 by undervolt

### ISSUE THREAD

**Issue by amithiel** [georgewhewell/undervolt#142]
Hi there,

using Manjaro with kernel 5.9 and undervolt 0.3.0 , just checked my logs and i get this error several times:
```
msr: Write to unrecognized MSR 0x150 by undervolt
                            Please report to x86@kernel.org
```
Searching Manjaro foruns, this user explains a bit:

> Linux 5.9 is coming along with annoying and frustrating changes related to MSR writes, for now it’s only kernel “spam” messages, but later versions will likely contain some kind of restriction for writes to MSR, so no easy way to undervolt or overclock in userspace.

I'm not very technical, so what does this mean? in the near future we won't be able to undervolt the cpu using this utility?

**Comment by georgewhewell** [comment]
it's just a warning, maybe will not be allowed in future kernel versions
