### ISSUE TITLE
how do 'powerlimit' and 'temp' options work?

### ISSUE THREAD

**Issue by kylebakerio** [georgewhewell/undervolt#144]
Documentation is unclear. I've never used those features in the past, but wondering how they are implemented and how to use them.

**Comment by georgewhewell** [comment]
added in 5910580

**Comment by kylebakerio** [comment]
That is helpful! But would be good id that description was clearly connected to the option settings themselves, and/or if examples were given. Don't know if I would have easily connected those dots reading that small bit of blurb.
