### ISSUE TITLE
we need a way to add notes per-model

### ISSUE THREAD

**Issue by kylebakerio** [georgewhewell/undervolt#145]
for instance, on the G5 5590 I just added, once you upgrade the bios to 1.12, 1.13, you have to go through a process in the bios of switching back to default settings to get undervolting enabled again. Once in 1.14, it may be locked forever, though I have seen one git repo walking through a complex downgrade procedure. Would be nice if there was a way to add that. Perhaps adding a wiki to the repo?

**Comment by georgewhewell** [comment]
That's a good idea, we should collate this info somewhere. I've enabled the wiki, anyone should be able to edit. Feel free to create a page for your device, i will close any issue relating to that device and point to the wiki

**Comment by georgewhewell** [comment]
thanks!
