### ISSUE TITLE
works on Dell G3 3579 with 1.14 BIOS

### ISSUE THREAD

**Issue by wastee** [georgewhewell/undervolt#147]
I follow this wiki: https://github.com/georgewhewell/undervolt/wiki/Dell-G5-5590

Set bios settings to factory. And it works.

Hope this info will help someone.

---------

OS: Arch Linux x86_64 
Host: G3 3579 
Kernel: 5.11.1-xanmod2-cacule-2-cacule-uksm 
Uptime: 3 mins 
Packages: 2626 (pacman), 27 (flatpak) 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: GNOME 3.38.3 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Papirus [GTK2/3] 
Terminal: tilix 
CPU: Intel i5-8300H (8) @ 4.000GHz 
GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
GPU: Intel UHD Graphics 630 
Memory: 1857MiB / 31955MiB

**Comment by marcosfons** [comment]
It worked, thanks!
