### ISSUE TITLE
Does this work with KVM/QEMU?

### ISSUE THREAD

**Issue by KZDKM** [georgewhewell/undervolt#165]
This is a dumb question but
I heard that undervolting is troublesome with virtualizations stuff
Does this work with KVM + Windows / MacOS guest systems?

**Comment by Reutertu3** [comment]
I'm not exactly sure what you mean. My machine is undervolted and has no issues running VMs.
Hosting VMs isn't a case where undervolting shows particulary odd behavior. It can be plenty stressful however, so an unstable system will crash more often compared to light loads. 

If you need a rock solid system then tinkering too much with undervolting is not advisable anyway.

**Comment by georgewhewell** [comment]
yes, should not make any difference
