### ISSUE TITLE
Macbook air mid 2013 | Failed to apply core

### ISSUE THREAD

**Issue by loss-and-quick** [georgewhewell/undervolt#171]
I tried `sudo undervolt --core -100 --cache -100` ,but there is a error `ERROR:root:Failed to apply core: set -99.609375, read 0.0`

**Specs**:
- Distro: arch linux
- Kernel: 5.18.14-zen1-1-zen
- CPU: Intel i5-4250U (4) @ 2.600GHz

**Comment by loss-and-quick** [comment]
Msr was deactivated

**Comment by Teloshav** [comment]
> Msr was deactivated

Hello @loss-and-quick ! I've been trying to fix this identical issue and I have NO idea what you mean by this.

Can you please explain what this is (or at least how you fixed it)?

I even have a Intel i5-4250U CPU!

Hope you can help.

- Teloshav

**Comment by loss-and-quick** [comment]
@Teloshav, check this [issue](https://github.com/georgewhewell/undervolt/issues/91)
in my case, i patched my dumped bios to solve this issue
