### ISSUE TITLE
Power limit is not permanent

### ISSUE THREAD

**Issue by x51don** [georgewhewell/undervolt#178]
Hi,

I'm "usinng undervolt -p1 40 30" and it is changing power limit to 40W for a while, but when I stress CPU for longer time it reverts to 45W.

It stays 40W when there is no load on the CPU.

**Comment by georgewhewell** [comment]
yes, sometimes your computers SMC will reset the controls. you can use the systemd timer described here to re-apply continually: https://github.com/georgewhewell/undervolt#running-automatically-on-boot-systemd
