### ISSUE TITLE
How do ThrottleStop's FIVR Control names map to those of undervolt?

### ISSUE THREAD

**Issue by ljez** [georgewhewell/undervolt#180]
This is not any issue in the code, just a question.  Since there's an option of using ThrottleStop's ini file, I assume there is a mapping between its FIVR Control names and those of undervolt?  I have two identical computer's, one running Windows and the other Linux.  On Windows, in ThrottleStop, in FIVR I see CPU Core, CPU Cache, Intel GPU, iGPU Unslice, and System Agent.  The first three are clear, but how do the last two map to undervolt's Uncore and Analog I/O?  Thanks in advance for clarifying this.

**Comment by georgewhewell** [comment]
exactly, yes 👍 
it seems like the last two do not affect power consumption much, and cause instability if lowered too much, i would avoid setting them
