### ISSUE TITLE
trying to set cpu and cache to -100, gives ERROR:root:Failed to apply core: set -99.609375, read 0.0

### ISSUE THREAD

**Issue by infopcgood** [georgewhewell/undervolt#181]
Motherboard: ASRock H410M-HVS
CPU : i5-10400
System : Debian 12

every command is run with sudo. I installed the msr-tools package.
this is the result of `sudo undervolt -r`, if needed. Is there a way I can fix this, or do I need to manually add support my hardware?
`temperature target: -0 (100C)
core: 0.0 mV
gpu: 0.0 mV
cache: 0.0 mV
uncore: 0.0 mV
analogio: 0.0 mV
powerlimit: 134.0W (short: 0.00244140625s - enabled) / 65.0W (long: 28.0s - enabled) [locked]`

**Comment by georgewhewell** [comment]
I haven't heard of any success on desktop platforms, sorry :(
