### ISSUE TITLE
Instruction how to reset settings to default values / how to delete undervolt.

### ISSUE THREAD

**Issue by A1exKH** [georgewhewell/undervolt#190]
I've checked in the internet, but didn't find any information about how to delete undervolt or reset all settings back to default.

Any feedback is appreciated.

**Comment by kisku** [comment]
I used **pip uninstall undervolt**, for uninstalling/removing undervolt from the ubuntu system. But I am not sure about resetting it to default state.

**Comment by georgewhewell** [comment]
the settings are not persistant across reboot- just remove the package and reboot

**Comment by A1exKH** [comment]
I didn't find any way how to reset settings. 
I've just deleted it with `pip uninstall undervolt` and rebooted the system.
