### ISSUE TITLE
github lenovo-throttling-fix

### ISSUE THREAD

**Issue by DEvil0000** [georgewhewell/undervolt#31]
There is a different tool on github called [lenovo-throttling-fix](https://github.com/erpalma/lenovo-throttling-fix).
Its doing the same and more. How about joining the effort on that one?

**Comment by georgewhewell** [comment]
I think there a quite a few scripts like this- they're all a bit different. The one you posted seems to have more features but also is quite a bit more complex and requires external dependencies. A nice thing about this version is that it's a single file with no dependencies required other than python :)
