### ISSUE TITLE
[RFE] Kaby Lake R support

### ISSUE THREAD

**Issue by martinhoyer** [georgewhewell/undervolt#38]
Hi,
I just tried to run undervolt on Carbon X1 Gen 6 with i7-8650U. Doesn't seem to be working. Can we expect support for these cpu's in the future?

temperature target: -20 (80C)
core: 0.0 mV
cache: 0.0 mV
analogio: 0.0 mV
uncore: 0.0 mV
gpu: 0.0 mV

**Comment by georgewhewell** [comment]
Hm- your CPU was reported working by another user. The output you posted is normal on the first run- you have to experiment a bit to find offsets that work on your system. If you try running `undervolt -r --core -10 --cache -10`, do the core and cache voltages change?

**Comment by martinhoyer** [comment]
Aaah, my bad! It does work indeed.
