### ISSUE TITLE
Problems on XPS 15 9550

### ISSUE THREAD

**Issue by ErikssonEivind** [georgewhewell/undervolt#41]
Hi! I'm trying to use the undervolt but I keep getting errors. I'm on a XPS 15 9550 and I have disabled secure boot in BIOS.

When i run "undervolt --read" i get: OSError: [Errno 1] Operation not permitted: '/dev/cpu/0/msr'

I then try with "sudo undervolt --read" and get: sudo: undervolt: command not found

What else can i try?
Maybe I'm using it completely wrong? 

Regards
Ejje

**Comment by georgewhewell** [comment]
try: `sudo $(which undervolt)`

**Comment by ErikssonEivind** [comment]
> try: `sudo $(which undervolt)`

Thanks! That did the trick
