### ISSUE TITLE
Why run the timer every 30 seconds?

### ISSUE THREAD

**Issue by Utini2000** [georgewhewell/undervolt#45]
I really like your script and how simple and effective it is.
How ever, running it every 30 seconds makes me wonder.

Wouldn't it be enough to just run it after booting and after comming back from suspend? 
Why would you run the script constantly every 30 seconds?

**Comment by georgewhewell** [comment]
Hi, I think this was added because there are other events that trigger the system firmware to reset the voltages such as dock/undock (#10) which are not supported as triggers by systemd. This seemed simplest way to solve it

**Comment by Utini2000** [comment]
Hey @georgewhewell ,
I understand that and already expected this to be the reason. 
But I find spamming the system with executing a script every 30 seconds a bit too much?
Isn't there some smarter solution which uses less resources? Maybe event monitoring?

**Comment by georgewhewell** [comment]
Yeah, event-based would be better! I couldn't see how to do this without requiring another piece of software though (eg, `acpid`). Perhaps a `udev` rule to trigger the systemd service could be enough, but I don't have a laptop with docking station to test this. Let's keep this ticket open to track progress on this.

**Comment by JHrenyk** [comment]
I just used a timer to apply the undervolt a few minutes after startup and wake up and that has seemed to work just fine.

**Comment by toverux** [comment]
@JHrenyk would you like to share it? :)

**Comment by JHrenyk** [comment]
I'd love to. I should be able to share it tonight. What's the best way to post it? 

EDIT: Ok so I made a repository (https://github.com/JHrenyk/Undervolt-Timer) that contains what I use to get my undervolt to work on start and after suspend. Give it a look over.

**Comment by toverux** [comment]
Thanks a lot! Will try that!

> What's the best way to post it?

You could have just pasted the files here if you don't want to keep a repo for that :)
