### ISSUE TITLE
Add --version to the CLI interface

### ISSUE THREAD

**Issue by pmav99** [georgewhewell/undervolt#47]
I think it would be a useful addition to the Command line interface. 

``` python
__version__ = '0.3.1'
# ...
    parser.add_argument('--version', action='version', version='%(prog)s version}'.format(version=__version__))
```

The only downside is that you need to either update the version in both setup.py and undervolt.py or use one of the solutions mentioned [here](https://packaging.python.org/guides/single-sourcing-package-version/). FYI I've used bumpversion and it works out just fine

If you want, I can make a pull request.

**Comment by georgewhewell** [comment]
Yeah, we should do this- good idea. I think we can use option 6- just set `__version__` in undervolt.py and import in setup.py. Pull request would be much appreciated :)
