### ISSUE TITLE
undervolting the discreet gpu

### ISSUE THREAD

**Issue by skarakulak** [georgewhewell/undervolt#54]
Hi,
My laptop has a GTX1050Ti discreet GPU in addition to the intel GPU. When we undervolt the GPU, it seems to undervolt only the intel GPU. Is there a way to undervolt the discreet GPU as well?

**Comment by georgewhewell** [comment]
I don't think this is possible (certainly not with this tool) under linux. You probably have to flash a custom BIOS to your GPU if you want to adjust voltage etc
