### ISSUE TITLE
Works on Lenovo Thinkpad X1 Carbon Generation 4

### ISSUE THREAD

**Issue by tsoernes** [georgewhewell/undervolt#55]
Confirmed

**Comment by auyer** [comment]
@tsoernes can you inform the CPU used ? Example: Intel i5-5250U

**Comment by tsoernes** [comment]
Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz

man. 10. jun. 2019 kl. 21:20 skrev Rafael Passos <notifications@github.com>:
