### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by newtonsart** [georgewhewell/undervolt#72]
$ sudo python3 ~/Downloads/undervolt/undervolt.py --read
temperature target: -0 (100C)
Traceback (most recent call last):
  File "/home/lolart/Downloads/undervolt/undervolt.py", line 289, in <module>
    main()
  File "/home/lolart/Downloads/undervolt/undervolt.py", line 284, in main
    voltage = read_offset(plane)
  File "/home/lolart/Downloads/undervolt/undervolt.py", line 178, in read_offset
    write_msr(value_to_write)
  File "/home/lolart/Downloads/undervolt/undervolt.py", line 53, in write_msr
    os.write(f, pack('Q', val))
OSError: [Errno 5] Input/output error

im using an ASUS A53S
sudo lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               42
Model name:          Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
Stepping:            7
CPU MHz:             1146.933
CPU max MHz:         3000.0000
CPU min MHz:         800.0000
BogoMIPS:            4789.58
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d

sudo ls /dev/cpu/*/   
/dev/cpu/0/:
msr

/dev/cpu/1/:
msr

/dev/cpu/2/:
msr

/dev/cpu/3/:
msr

thank you very much for your help

**Comment by georgewhewell** [comment]
Your CPU is not supported, will not work (see #22). Interesting that temperature seems to read ok- maybe we can support temp control only on older cpu
