### ISSUE TITLE
OnUnitActiveSec not needed?

### ISSUE THREAD

**Issue by tvld** [georgewhewell/undervolt#76]
In documentation you mention:
```
# Run every 30 seconds
OnUnitActiveSec=30
```
But why is that? Once set, the undervolt should stay in place until reboot.. right?

**Comment by retromuz** [comment]
Think about resume after sleep.

**Comment by tvld** [comment]
What about using one of these?
```
After=suspend.target
#After=hibernate.target
#After=hybrid-sleep.target
```

**Comment by georgewhewell** [comment]
Dock/undock, add/remove AC and other things can cause it to get reset

**Comment by tvld** [comment]
Ah, so just a multi-pre caution?  I would run it every 10 minutes or so then. No need to have this high frequency?

Will close as it seems not a bug but a feature )))
