### ISSUE TITLE
Confirm to work on Dell Inspiron 15-7537

### ISSUE THREAD

**Issue by amerlo94** [georgewhewell/undervolt#82]
It works out of the box on a Dell Inspiron 15-7537 with Ubuntu 19.04, equipped with an Intel i7 4500U.

This config seems to be stable.

`sudo undervolt --core -50 --cache -50 --gpu -75`

Undervolting the CPU with a 100 mV offset leads to a CPU freeze.

Thank for the software.

**Comment by georgewhewell** [comment]
Thanks for report. Please open PR if you'd like to add to compatibility table
