### ISSUE TITLE
Bad Line Start DRM_KMS_HELPER

### ISSUE THREAD

**Issue by ngowilliam1** [georgewhewell/undervolt#84]
I'm getting the following issue while doing: undervolt --read

libkmod: ERROR ../libkmod/libkmod-config.c:656 kmod_config_parse: /etc/modprobe.d/local.conf line 1: ignoring bad line starting with 'drm_kms_helper'
temperature target: -3 (97C)
core: 0.0 mV
cache: 0.0 mV
analogio: 0.0 mV
uncore: 0.0 mV
gpu: 0.0 mV

**Comment by georgewhewell** [comment]
I think you might have syntax errors in your `/etc/modprobe.d/local.conf`- these are shown when undervolt tries to run `modprobe msr`
