### ISSUE TITLE
Advantages over intel-undervolt 

### ISSUE THREAD

**Issue by lhk** [georgewhewell/undervolt#85]
The Readme presents this project as a thin wrapper on top of Intel-undervolt. Apart from small differences in the cli, are there reasons to use this project over the other? Are there differences in the featureset?

**Comment by georgewhewell** [comment]
The project referenced (https://github.com/mihic/linux-intel-undervolt) is purely informational- there is no tool or CLI.

**Comment by lhk** [comment]
Oh sorry, my bad. I had found this at the same time as your project : https://github.com/kitsunyan/intel-undervolt

Since the naming is so similar, I thought you were linking to it.

So I assume the two projects (undervolt and intel-undervolt) are pretty much in direct competition? Two implementations of the same functionality?

**Comment by georgewhewell** [comment]
Yes they do pretty much same thing. The project you linked seems to have more features but requires compiling and bit more complex to distribute
