### ISSUE TITLE
Works on Dell Precision 5540 with i5-9400H

### ISSUE THREAD

**Issue by godenji** [georgewhewell/undervolt#87]
`sudo ./undervolt.py --core -125 --cache -125 --gpu -75`
`sudo ./undervolt.py --read`
> temperature target: -0 (100C)
core: -125.0 mV
gpu: -75.2 mV
cache: -125.0 mV
uncore: 0.0 mV
analogio: 0.0 mV

Thanks :+1:

**Comment by georgewhewell** [comment]
thanks!
