### ISSUE TITLE
Inquiry sheet

### ISSUE THREAD

**Issue by youyouyong** [georgewhewell/undervolt#88]
1;  ThinkPad X1 Extreme           Part Number: 20MFCTO1WW                qty 10
Turbo Boost, 9MB Cache)
Operating System : Windows 10 Pro 64
Operating System Language : Windows 10 Pro 64 English
Display : 15.6” 4K UHD HDR (3840 x 2160) IPS multi-touch, anti-reflective / anti-smudge, 400 nits
Memory : 16 GB (8GB + 8GB) DDR4 2666MHz
Graphic Card : NVIDIA® GeForce® GTX 1050 Ti Max-Q 4GB
Camera : IR & 720p HD Camera with microphone
Keyboard : Backlit Keyboard - US English
Fingerprint Reader : Fingerprint Reader
Security Chip : Hardware dTPM
TPM Setting : Hardware dTPM2.0 Enabled
RAID Config : No
First Hard Drive : 512GB Solid State Drive PCIe-NVMe OPAL2.0 M.2
HDD Total Capacity : 512GB
Battery : 4 cell Li-Polymer 80Wh
Power Cord : 135W AC Adapter
Wireless : Intel 9560 802.11AC vPro (2 x 2) & Bluetooth 5.0
Ethernet Dongle : Full size Ethernet Extension Connector
Package Box : Standard Packaging
Language Pack : Publication-English
Enterprise Ready Preload : None
Warranty : 1 Year Depot or Carry-in

2,ThinkPad X1 Carbon 7th Generation        Part Number: 20QDCTO1WW           qty 20
Operating System Language : Windows 10 Pro 64 English
Memory : 16GB LPDDR3 2133MHz (Onboard)
Hard Drive : 512GB Solid State Drive M.2 PCIe-NVMe, Opal
Display : 14.0" FHD (1920 x 1080) 400 nits, IPS, low power, anti-glare
Graphic Card : Integrated Intel® UHD Graphics 620
Fingerprint Reader : Fingerprint Reader
Top Cover Material : Carbon Fiber with Black Paint
Color : Black
Camera : 720p HD Camera with microphone
TPM Setting : Enabled Discrete TPM2.0
Battery : 4 cell Li-Polymer, 51Wh
Power Cord : 65W AC (2 pin) - USB Type C
Wireless : Intel® 9560 802.11AC (2 x 2) & Bluetooth® 5.0
Keyboard : Backlit Keyboard - US English
Integrated Wireless Antenna : WLAN Antenna
Ethernet Dongle : RJ45 Extension Connector
vPro Certified Model : vPro Certified
Display Panel : 14.0" FHD (1920x1080) IPS Anti-Glare 400nits Low Power, 720p HD Camera with Shutter, Mic, Black
Package Box : Retail Packaging
Absolute BIOS Selection : BIOS Absolute Enabled
Language Pack : Publication-English
Warranty : 1 Year Depot or Carry-in

3,ThinkPad X1 Carbon 7th Generation      Part Number: 20QDCTO1WW         qty 20
Memory : 8GB LPDDR3 2133MHz (Onboard)
Hard Drive : 256GB Solid State Drive M.2 PCIe-NVMe, Opal
Display : 14.0" FHD (1920 x 1080) 400 nits, IPS, low power, anti-glare
Graphic Card : Integrated Intel® UHD Graphics 620
Fingerprint Reader : Fingerprint Reader
Top Cover Material : Carbon Fiber with Black Paint
Color : Black
Camera : 720p HD Camera with microphone
TPM Setting : Enabled Discrete TPM2.0
Battery : 4 cell Li-Polymer, 51Wh
Power Cord : 65W AC (2 pin) - USB Type C
Wireless : Intel® 9560 802.11AC (2 x 2) & Bluetooth® 5.0
Keyboard : Backlit Keyboard - US English
Integrated Wireless Antenna : WLAN Antenna
Ethernet Dongle : RJ45 Extension Connector
Display Panel : 14.0" FHD (1920x1080) IPS Anti-Glare 400nits Low Power, 720p HD Camera with Shutter, Mic, Black
Package Box : Retail Packaging
Absolute BIOS Selection : BIOS Absolute Enabled
Language Pack : Publication-English
Warranty : 1 Year Depot or Carry-in

**Comment by georgewhewell** [comment]
Not sure what the issue is here- all the machines listed should be supported if that's what you're asking.
