### ISSUE TITLE
Can anyone confirm if this works with old Core2Duo's? (Laptop)

### ISSUE THREAD

**Issue by DwarfFighterCleric** [georgewhewell/undervolt#89]
I used to undervolt on Windows using RM Clock, totally forgot about it on Linux. I've been limiting my clocks (for browsing only 1.20GHz but it is still reaching 70ºC on youtube, and the dedicated AMD GPU idle at 75ºC...)
Be mindful that I use my laptop permanently in a "live" mode for other reasons (not installed on disk) so a kernel-rebuild or anything that requires rebooting is out of the question for me.
Any suggestions?
(anything for the AMD Radeon GPU would be nice too...)

**Comment by georgewhewell** [comment]
Sorry, this tool will only work on gen 4+. GPU not supported either
