### ISSUE TITLE
Uncore voltage & temperature target ?

### ISSUE THREAD

**Issue by ghost** [georgewhewell/undervolt#96]
Using `/etc/sv/undervolt/run` with
```
#!/bin/sh
undervolt --core 140 --cache 140 --gpu -70
```

`sudo undervolt -r `
```
temperature target: -10 (90C)
core: -139.65 mV
cache: -139.65 mV
analogio: 0.0 mV
uncore: -70.31 mV
gpu: -70.31 mV
```

Is uncore linked to gpu and what is the purpose of temperature target ? the description is confusing to me, what does it do if I set the target to 40 degrees for example ?

Thanks in advance

**Comment by georgewhewell** [comment]
no, uncore is "everything else"- in my experience it does not save much (any?) energy to undervolt it.

temp target- this will tell the CPU to drop voltage/frequency to keep temperature under this amount at all costs. you can set this to a lower temp than normal and cpu will not go into very high freq modes (use a lot of energy)
