### ISSUE TITLE
[Device support confirmation] Works on HP Omen 15 (dc0019ur)

### ISSUE THREAD

**Issue by UnicodeMan** [georgewhewell/undervolt#97]
I can confirm that this application works on HP 15-dc0019ur, with Intel® Core™ i5-8300H processor.
Laptop information: https://support.hp.com/nz-en/document/c06063989

![image](https://user-images.githubusercontent.com/25935211/76004434-2602f700-5f12-11ea-8eef-5f3b2be4284b.png)

You can add this laptop to the list of supported products.

Thank you for this application :+1:

**Comment by georgewhewell** [comment]
Thanks! please open PR adding your machine if you want added to support list :)
